### ISSUE TITLE
Version 0.9.0 is not working

### ISSUE THREAD

**Issue by pnxs** [gerlachch/dots-explorer#15]
When starting, the program terminates immediately:

```
$ ./dots-explorer 
terminate called after throwing an instance of 'std::runtime_error'
  what():  attempt to access invalid property: selectedView
```

Checked version 0.8.0, which is OK.
Used compiler: gcc-Version 11.2.1 20220115 (Gentoo 11.2.1_p20220115 p4)

**Comment by gerlachch** [comment]
I can confirm that this is a regression, which is caused by improper handling of incomplete (or fresh) configuration files.

As a workaround until the issue is fixed, you should be able to create the configuration file with v0.8.0 and then switch to v0.9.0 afterwards.
