### ISSUE TITLE
Program exits automatically at startup

### ISSUE THREAD

**Issue by Noiro3940** [gerlachch/dots-explorer#24]
When the program is started it crashes. Unfortunately, a log file is not created.

**Comment by gerlachch** [comment]
Does the issue persist when you rename the `dots-explorer.ini` to something else?

Under Windows you can find it under `%USERPROFILE%\.dots-explorer\`.

If it does resolve the crash, please upload the configuration for analysis.

**Comment by Noiro3940** [comment]
Yes the issued is persist, when i rename the dots-explorer.ini or when i remove this file. If i start the dots-explorer with admin rights the same thing.

**Comment by gerlachch** [comment]
Thank you for the feedback. I will see what I can do about it.

**Comment by hlippke** [comment]
I have the same issue on a "clean" Windows 10 21H2.
- extract the exe to Downloads Folder
- Windows refuses to start the application because it's not signed, confirm to run anyway
- Window frame appears and disappears after few seconds

**Comment by gerlachch** [comment]
Until I can investigate the issue further, can you try to install the latest [Visual C++ Redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe)?

In general, the application has very few runtime dependencies, but this is something that might be missing on some systems.

**Comment by Noiro3940** [comment]
After install the Visual C++ Redistributable tool, unfortunately no changes.
![image](https://user-images.githubusercontent.com/79352705/224571594-b2a1d3ca-0966-4025-b189-37ab495605b2.png)
I have here the WindowsLog from this crash.


![Fehler_Dots_explorerV1_0_0](https://user-images.githubusercontent.com/79352705/224571773-0ad1cfb2-607d-499e-80d6-3ba5cd28d51d.png)

Maybe it helps to limit the error.

**Comment by Noiro3940** [comment]
If i delet the Folder .dots-explorer and start than die Exe-file, a new Folder ".dots-explorer" will be createt, but not a ini-file.

**Comment by gerlachch** [comment]
Thank you again for the feedback.

Can you try again with the attached version? It should not fix the issue, but create an error log next to the executable called "dots-explorer.crash". Maybe this will get us some insight into the problem.

[dots-explorer_v1_0_1-PREVIEW-1..zip](https://github.com/gerlachch/dots-explorer/files/10959350/dots-explorer_v1_0_1-PREVIEW-1.zip)

**Comment by Noiro3940** [comment]
[dots-explorer_Crashlog.zip](https://github.com/gerlachch/dots-explorer/files/10961532/dots-explorer_Crashlog.zip)

Here are the crash log.

**Comment by gerlachch** [comment]
Thank you very much. I now know what the cause of the issue is and will release a hotfix shortly.

In the meantime, you can fix the problem on your end, by installing the time zone database from IANA. I would recommend that anyway to be able to view timestamps in your local time, but of course the application should be able to run without it.

To install the database, download it from [here](https://data.iana.org/time-zones/releases/tzdata2022g.tar.gz) and extract all files into a folder called "tzdata" under your Windows "Downloads" folder.

**Comment by Noiro3940** [comment]
thanks for the info. but in your link archive is the windowsZones.xml -file. 

Better is to use this file: 
[tzdata.zip](https://github.com/gerlachch/dots-explorer/files/10973170/tzdata.zip)

**Comment by gerlachch** [comment]
Oh, you are right. I didn't link the Windows version. My bad. Thank you for the correction.
